-- ==========================================
-- AttendifyAI Database Schema & Initialization
-- Compatible with PostgreSQL (Supabase)
-- Matches exact physical ER diagram specifications
-- ==========================================

-- Enable pgvector extension for AI face embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. USERS TABLE (Credentials and authorization roles)
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL, -- 'admin', 'teacher', 'student'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TEACHERS TABLE (Teacher profiles linked to user accounts)
CREATE TABLE IF NOT EXISTS teachers (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    employee_number VARCHAR(255) UNIQUE NOT NULL,
    department VARCHAR(255),
    phone VARCHAR(255),
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. SECTIONS TABLE (Academic batches/sections assigned to class teachers)
CREATE TABLE IF NOT EXISTS sections (
    id SERIAL PRIMARY KEY,
    sec_name VARCHAR(255) NOT NULL,
    semester VARCHAR(255), -- Note: VARCHAR type as per ER diagram
    department VARCHAR(255),
    capacity INT,
    class_teacher INT REFERENCES teachers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. STUDENTS TABLE (Student profiles linked to user accounts and sections)
CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    roll_number VARCHAR(255) UNIQUE NOT NULL,
    section_id INT REFERENCES sections(id) ON DELETE SET NULL,
    branch VARCHAR(255),
    semester INT, -- Note: INT type as per ER diagram
    phone VARCHAR(255),
    admission_year INT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. STUDENT FACES TABLE (Stores 512-dimension face vectors/embeddings generated by AI Service)
CREATE TABLE IF NOT EXISTS student_faces (
    id SERIAL PRIMARY KEY, -- Note: Separate auto-increment PK as per ER diagram
    student_id INT REFERENCES students(id) ON DELETE CASCADE,
    section_id INT REFERENCES sections(id) ON DELETE CASCADE,
    image_url TEXT,
    embedding vector(512) NOT NULL, -- Note: pgvector vector type as per ER diagram
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. CLASSROOMS TABLE (Venues/classrooms where lectures are conducted)
CREATE TABLE IF NOT EXISTS classrooms (
    id SERIAL PRIMARY KEY,
    room_number VARCHAR(255) UNIQUE NOT NULL,
    building VARCHAR(255),
    capacity INT
);

-- 7. SUBJECTS TABLE (Academic curriculum subjects)
CREATE TABLE IF NOT EXISTS subjects (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    department VARCHAR(255),
    semester INT -- Note: INT type as per ER diagram
);

-- 8. TEACHER SUBJECT MAPPING (Links teachers to specific subjects and sections)
CREATE TABLE IF NOT EXISTS teacher_subject_map (
    teacher_id INT REFERENCES teachers(id) ON DELETE CASCADE,
    subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,
    section_id INT REFERENCES sections(id) ON DELETE CASCADE,
    PRIMARY KEY (teacher_id, subject_id, section_id)
);

-- 9. TIMETABLE SCHEDULES (Defines scheduled classes for academic periods)
CREATE TABLE IF NOT EXISTS timetable (
    id SERIAL PRIMARY KEY,
    section_id INT REFERENCES sections(id) ON DELETE CASCADE,
    subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,
    teacher_id INT REFERENCES teachers(id) ON DELETE CASCADE,
    classroom_id INT REFERENCES classrooms(id) ON DELETE SET NULL,
    day_of_week INT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0 = Sunday, 1 = Monday, ..., 6 = Saturday
    period_no INT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    semester INT,
    academic_year VARCHAR(255),
    valid_from DATE,
    valid_to DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. ATTENDANCE SESSIONS (Instances of active or completed attendance trackers)
CREATE TABLE IF NOT EXISTS attendance_sessions (
    id SERIAL PRIMARY KEY,
    section_id INT REFERENCES sections(id) ON DELETE CASCADE,
    subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,
    teacher_id INT REFERENCES teachers(id) ON DELETE CASCADE,
    classroom_id INT REFERENCES classrooms(id) ON DELETE SET NULL,
    period_no INT,
    method VARCHAR(255),
    class_date DATE NOT NULL DEFAULT CURRENT_DATE,
    qr_token VARCHAR(255),
    session_status VARCHAR(255),
    classroom_image TEXT, -- Note: Added in ER diagram
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 11. ATTENDANCE RECORDS (Marks presence/absence status of each student for a session)
CREATE TABLE IF NOT EXISTS attendance_records (
    id SERIAL PRIMARY KEY,
    session_id INT REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id INT REFERENCES students(id) ON DELETE CASCADE,
    status VARCHAR(255) NOT NULL DEFAULT 'absent',
    confidence FLOAT8, -- Note: float8 (double precision) as per ER diagram
    method TEXT,
    marked_by TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_student_session UNIQUE (session_id, student_id)
);

-- 12. ATTENDANCE FACES (Verification/audit table for face detection results)
CREATE TABLE IF NOT EXISTS attendance_faces (
    id SERIAL PRIMARY KEY,
    session_id INT REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id INT REFERENCES students(id) ON DELETE CASCADE,
    image_url TEXT,
    confidence NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_students_section ON students(section_id);
CREATE INDEX IF NOT EXISTS idx_student_faces_section ON student_faces(section_id);
CREATE INDEX IF NOT EXISTS idx_timetable_lookup ON timetable(teacher_id, day_of_week, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_attendance_records_lookup ON attendance_records(session_id, student_id);
